name: Health check

on:
  push

jobs:
  check-health:
    steps:
      - name: Check the deployed service URL
        uses: jtalk/url-health-check-action@v2
        with:
          url: http://fso-pokedex-exercise.herokuapp.com/
